### ISSUE TITLE
Kitten panel (color-changer) should disappear when user clicks anywhere other than a kitten

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/number-pairs#27]
Currently, the kitten panel is visible at all times. When a user clicks in the grass or presses the organize/commutative property button, or anywhere other than a kitten, the panel should disappear.

**Comment by marlitas** [comment]
Committed above. @catherinecarter can you test it out and see what you think.

@pixelzoom can you review. I think I followed convention for this but want to double check.

**Comment by catherinecarter** [comment]
Looks and acts great to me!

**Comment by pixelzoom** [comment]
Did you want clicking _anywhere_ to deselect the kitten? For example, collapsing an accordion box, etc.   If so, then your implementation looks nice.

But it also might be reasonable to require the user to deselect by clicking in the "counting area", and that would probably require adding the PressListener to `countingAreaNode` in NumberPairsScreenView.

**Comment by catherinecarter** [comment]
That's a good point, @pixelzoom. If a user opens or closes an accordion box, I don't know what I'd expect. I don't think it's a huge deal since every time a kitten is touched, the color-changing panel appears. So if it disappears when an accordion box is open or closed, my eyes are likely at the accordion box. 

Do you have a recommendation?

**Comment by marlitas** [comment]
Last we talked @catherinecarter you had mentioned that you wanted the panel to disappear anytime a user clicked outside of the counting area as well. Including buttons such as the organize, commutative, and scene selection. If we are removing the focus in those situations I would assume we also want to remove focus when we interact with accordion boxes. Unless that opinion has changed since seeing it in practice?

**Comment by pixelzoom** [comment]
To clarify... My comment was not intended to be specific to accordion boxes, or imply that something about the accordion boxes requires maintaining the selection.  It may be just fine as is.  I mentioned it only because it seemed a little odd to me that clicking outside the counting area would clear the selection in the counting area.   

For example, see Vector Addition, where vectors can be selected in the graph, and are deselected if you click somewhere in the graph.  That's important in Vector Addition, because things outside the graph (e.g. the Vector Values accordion box above the graph) are displaying things about the selected vector.

**Comment by catherinecarter** [comment]
You are correct, @marlitas that all the things you mentioned should result in the color-changer disappearing. I hadn't considered the accordion boxes. 

Not sure if it's possible to have the color-changer disappear with everything but the accordion boxes, and if not, I don't think it's a big deal. Let's discuss at standup.

**Comment by marlitas** [comment]
We discussed at standup and I still maintain that if we decide clicking outside of the counting area removes the selection in one situation, it should do it in all situations. It is possible to do what @catherinecarter is requesting in the code, but will create multiple special situations, essentially adding logic to press listeners for almost all of the buttons. I generally feel like that type of logic addition in the code indicates a strange UX. My preference would be to keep the logic straightforward and simple.

@catherinecarter would like to discuss with another designer before making a decision.

**Comment by pixelzoom** [comment]
Sorry to open a can of worms here.   

> It is possible to do what @catherinecarter is requesting in the code, but will create multiple special situations, essentially adding logic to press listeners for almost all of the buttons. My preference would be to keep the logic straightforward and simple.

I agree, and definitely recommend against an "everything but the accordion boxes" design for deselection. Either "click anywhere to deselect" or "click in counting object area to deselect".

**Comment by catherinecarter** [comment]
Thanks, @marlitas and @pixelzoom. I talked with @amanda-phet who pointed out that the alt-input behavior should also be considered. When a kitten has focus, it has the color-changing panel. When the user navigates outside the kitten counting area to any other element, including the accordion boxes, the color-changing panel is no longer the focus. 

So, the original statement is still valid that if a user clicks anywhere other than a kitten, the color-changing panel should disappear. 

Appreciate the considerations!

**Comment by marlitas** [comment]
Great. With that decision this issue is now ready to close. Thanks all!
